### ISSUE TITLE
Batching in RestockRequestManagerService.cs and more

### ISSUE THREAD

**Issue by AsValeO** [Azure-Samples/service-fabric-dotnet-web-reference-app#2]
1) Please explain in comments or somehow, how batching of RestockRequests works in `RestockRequestManagerService.cs`. I don't get it. As for me there is no batching in `RunAsync()`, just throttling with 1 sec delay. We still proccess 1 item per transaction here.
2) I've found this comment:
`/// TODO: Temporary property-injection for an IServiceProxyWrapper until constructor injection is available.`
Do some dependency injection support changes coming into SF?
3) Documentation about Actor's Event says that Events can be used only for communication between Actors and Clients. So `RestockRequestManagerService` and any other Reliable Service  count as Client?
`// Successfully added, register for event notifications for completion
await restockRequestActor.SubscribeAsync<IRestockRequestEvents>(this);`

**Comment by masnider** [comment]
Hi there, sorry it took so long for me to get back to you. 
1) At this point there isn't any batching at that stage in the sample. There's an old parameter there which gives you the idea because of how it is named, but you're right in that requests are still processed singly. We'll probably rename the property in an upcoming update, or introduce actual request batching which would be a larger change.
2) Yes. In our subsequent releases you should see improvements in dependency injection and unit testing for both actors and services. 
3) Yes in this context "client" means anywhere you have an actor proxy. It could be another Reliable Service, another Actor object, or some standalone code.
